insert into departments (department_name)
    values ('User Experience'),
           ('Backend Development'),
           ('DevOps'),
           ('Data Management'),
           ('Quality Assurance');

insert into roles (role_title, salary, department_id)
    values ('UX Researcher', 56000.00, 1),
           ('UX Designer', 68000.00, 1),
           ('Frontend Developer', 78000.00, 1),
           ('UX Team Lead', 125000.00, 1),
           ('Backend Engineer', 84000.00, 2),
           ('Middle-stack Developer', 81000.00, 2),
           ('Backend Team Lead', 140000.00, 2),
           ('Cloud Architect', 105000.00, 3),
           ('System Administrator', 98000.00, 3),
           ('DevOps Team Lead', 187000.00, 3),
           ('Data Scientist', 105000.00, 4),
           ('Lead Data Scientist', 202000.00, 4),
           ('QA Analyst', 89000.00, 5),
           ('Testers', 58000.00 , 5),
           ('QA Lead', 130000.00, 5);

insert into employees (first_name, last_name, role_id, manager_id)
    values ('Elizabeth', 'Hughes', 4, null),
           ('Hattie', 'McRae', 7, null),
           ('James', 'Olson', 10, null),
           ('Joe', 'McCloud', 12, null),
           ('Laura', 'Dehaven', 15, null),
           ('Jacqueline', 'Holifield', 1, 1),
           ('Randolph', 'Boyd', 1, 1),
           ('Justin', 'Tharp', 2, 1),
           ('David', 'Koehler', 2, 1),
           ('Bianca', 'Mitchell', 3, 1),
           ('Martha', 'Parnell', 3, 1),
           ('Danny', 'Brown', 5, 2),
           ('Ron', 'Kuss', 5, 2),
           ('Kathy', 'Marshal', 6, 2),
           ('Russell', 'Davis', 6, 2),
           ('Lawrence', 'Santos', 8, 3),
           ('Jeffrey', 'Ogden', 9, 3),
           ('Lindsey', 'Wilson', 11, 4),
           ('John', 'White', 11, 4),
           ('Ruthann', 'Dougherty', 13, 5),
           ('Nicholas', 'Smith', 13, 5),
           ('Josephine', 'Griffin', 14, 5),
           ('Winston', 'Landry', 14, 5);